server:
  port: 0
  servlet:
    context-path: /


spring:
  application:
    name: user-server
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.253.89:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/exercise?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456


mybatis-plus:
  type-aliases-package: com.qf.*.entity
  mapper-locations: classpath:mapper/**/*.xml




logging:
  level:
    com.qf.exercise.user.mapper: debug
