spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.253.89:8848
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id : exercise-user
          uri: lb://user-server
          predicates:
            - Path=/api/user-server/**
          filters:
            - StripPrefix=1



server:
  port: 8888


logging:
  level:
    org.springframework.cloud.gateway: debug
